# locale_es.yml
---
- name: Configurar locale es_ES.UTF-8
  hosts: all
  tasks:
    - name: Habilitar es_ES.UTF-8 en locale.gen
      lineinfile:
        path: /etc/locale.gen
        regexp: '^#?es_ES.UTF-8 UTF-8'
        line: 'es_ES.UTF-8 UTF-8'
        state: present

    - name: Generar locales
      command: locale-gen

    - name: Establecer LANG
      lineinfile:
        path: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=es_ES.UTF-8'
        create: yes

    - name: Establecer LC_ALL
      lineinfile:
        path: /etc/default/locale
        regexp: '^LC_ALL='
        line: 'LC_ALL=es_ES.UTF-8'
        create: yes